name: Valgrind Test

on:
  pull_request:
  push:
    branches:
      - main      
            - dev
            
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64

    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        run: |
          sudo apt update
          sudo apt install -y libev-dev
      - name: Install Valgrind
        run: |
          sudo apt install valgrind
          echo "Valgrind installed"

      - name: Build Tests
        run: |
          make
          build/mash

      - name: Run Tests with Valgrind
        run: |
                    valgrind --leak-check=full --suppressions=./path/to/suppresion/my_app.supp --xml=yes --xml-file=unit_tests_valgrind.xml ./unit_tests_binary

      - name: Valgrind Memory check
        run: |
          echo "Checking Valgrind xml ..."
            ./check-memory.sh 
